# Generated by Django 4.0.4 on 2022-05-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projeto_tecnologias'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
