# Generated by Django 4.0.4 on 2022-06-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_noticia_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhocurso',
            name='imagem',
            field=models.ImageField(default='', upload_to='trabalhos/'),
        ),
        migrations.RemoveField(
            model_name='trabalhocurso',
            name='autor',
        ),
        migrations.AddField(
            model_name='trabalhocurso',
            name='autor',
            field=models.ManyToManyField(related_name='Autor', to='portfolio.pessoa'),
        ),
    ]
