# Generated by Django 4.0.4 on 2022-05-26 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_noticia_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='projeto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.projeto'),
        ),
    ]
