# Generated by Django 4.0.4 on 2022-06-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_trabalhocurso_imagem_remove_trabalhocurso_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhocurso',
            name='titulo',
            field=models.CharField(max_length=120),
        ),
    ]
